/*
AF-002 - SAS Import Object Events Example

Repository-relative path:
    af-002-iot-aiot-for-sas-programmers/sas/sas_import_object_events.sas

GitHub URL:
    https://github.com/agentforgeframework-cpu/-agentforge-training/blob/main/af-002-iot-aiot-for-sas-programmers/sas/sas_import_object_events.sas

Raw URL:
    https://raw.githubusercontent.com/agentforgeframework-cpu/-agentforge-training/refs/heads/main/af-002-iot-aiot-for-sas-programmers/sas/sas_import_object_events.sas

Purpose:
    Import AI-assisted object telemetry generated by:
    python/webcam_object_telemetry.py

Expected CSV:
    data/webcam_object_events.csv

Fallback CSV:
    data/webcam_object_events_sample.csv

Instructions:
    1. Update the TELEMETRY_CSV macro variable below if needed.
    2. Run this program in SAS.
    3. Confirm that PROC PRINT, PROC FREQ, and PROC MEANS produce visible output.

Note:
    In SAS OnDemand for Academics, upload the CSV to your SAS Files area
    and update the path below to the uploaded file location.
*/

/* Update this path if your CSV is stored somewhere else. */
%let TELEMETRY_CSV = data/webcam_object_events.csv;

/*
Example Windows local path:
%let TELEMETRY_CSV = C:\AF-002\data\webcam_object_events.csv;

Example SAS OnDemand style path after upload:
%let TELEMETRY_CSV = /home/u12345678/webcam_object_events.csv;
*/

title "AF-002 Webcam Object Events Import" ;

proc import datafile="&TELEMETRY_CSV."
    out=work.webcam_object_events
    dbms=csv
    replace ;
    guessingrows=max ;
run ;

title "First Rows of Webcam Object Events" ;
proc print data=work.webcam_object_events(obs=20) ;
run ;

title "Detected Object Counts" ;
proc freq data=work.webcam_object_events ;
    tables object_detected source / nocum ;
run ;

title "Object Detection Confidence Summary" ;
proc means data=work.webcam_object_events n mean min max ;
    var confidence detection_count ;
run ;

title ;
