/*
AF-002 - SAS Import Telemetry Example

Repository-relative path:
    -agentforge-training/af-002-iot-aiot-for-sas-programmers/sas/sas_import_telemetry.sas

GitHub URL:
    https://github.com/agentforgeframework-cpu/-agentforge-training/blob/main/af-002-iot-aiot-for-sas-programmers/sas/sas_import_telemetry.sas

Raw URL:
    https://raw.githubusercontent.com/agentforgeframework-cpu/-agentforge-training/refs/heads/main/af-002-iot-aiot-for-sas-programmers/sas/sas_import_telemetry.sas

Purpose:
    Import webcam telemetry CSV generated by:
    python/webcam_telemetry_capture.py

Expected CSV:
    examples/webcam_telemetry.csv

Fallback CSV:
    data/webcam_telemetry_sample.csv

Instructions:
    1. Update the TELEMETRY_CSV macro variable below if needed.
    2. Run this program in SAS.
    3. Confirm that PROC PRINT and PROC MEANS produce visible output.

Note:
    In SAS OnDemand for Academics, upload the CSV to your SAS Files area
    and update the path below to the uploaded file location.
*/

/* Update this path if your CSV is stored somewhere else. */
%let TELEMETRY_CSV = examples/webcam_telemetry.csv;

/*
Example Windows local path:
%let TELEMETRY_CSV = C:\Users\Owner\Documents\#git\agentforgeframework-cpu\-agentforge-training\af-002-iot-aiot-for-sas-programmers\examples\webcam_telemetry.csv;

Example SAS OnDemand style path after upload:
%let TELEMETRY_CSV = /home/u12345678/webcam_telemetry.csv;
*/

title "AF-002 Webcam Telemetry Import" ;

proc import datafile="&TELEMETRY_CSV."
    out=work.webcam_telemetry
    dbms=csv
    replace ;
    guessingrows=max ;
run ;

title "First Rows of Webcam Telemetry" ;
proc print data=work.webcam_telemetry(obs=10) ;
run ;

title "Telemetry Summary" ;
proc means data=work.webcam_telemetry n mean min max ;
    var frame_number brightness motion_score ;
run ;

title "Telemetry Source Counts" ;
proc freq data=work.webcam_telemetry ;
    tables source / nocum ;
run ;

title ;
